Code fix for K8s fetch failure
ansible/ansible-kubernetes-modules pull request #37
Opened 2018-09-06 08:00 UTC by hprateek

Previous code was not working. A final fix to make this repo working and then we can freeze this repo. Request owner to merge this change as it fixes previous bugs.

2018-09-06 08:01 UTC, hprateek43 reviewed
k8s_extensions_v1beta1_deployment: Failed to patch object: unrecognized type: string #22.

Fixes this bug

2018-09-06 19:53 UTC, fabianvf requested changes
I don't have any real objection to this change, I think there were some changes brought in that are unrelated though. 

Just FYI this repo is deprecated in favor of the `k8s` module that shipped in Ansible 2.6 (which is the combined `openshift_raw` + `k8s_raw`  from 2.5)

2018-09-06 19:53 UTC, fabianvf commented on README.md
> -# DEPRECATED
Could you add this section back?

2018-09-06 19:53 UTC, fabianvf commented on ansible-kubernetes-modules.spec
>  Name:           ansible-kubernetes-modules
This file as well, I don't think we should be reverting the changelog

2018-09-06 19:53 UTC, fabianvf commented on module_utils/k8s_common.py
> -                return_attributes[self.kind] = k8s_obj.to_dict() if k8s_obj else {}
Were these removed on purpose? I think `k8s_obj` has a chance of being `None` which is why these guards were put in place.

2018-12-19 17:54 UTC, gundalow commented
Deprecated, please use the `k8s` modules that ship with Ansible

2018-12-19 17:54 UTC, closed without merging